import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Team Shur&rsquo;tugals</title>
        <meta name="description" content="Generated by team Shur'tugals" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Team Shur&rsquo;tugals
        </h1>
      </main>

    </div>
  )
}

export default Home;
